name = "eindhoven"
version = "0.1.0"
defaultTargets = ["Eindhoven"]

[[lean_lib]]
name = "Eindhoven"

[[require]]
name = "verbose"
git = "https://github.com/PatrickMassot/verbose-lean4.git"
rev = "bump4.17"
